name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Run Api
    runs-on: ubuntu-latest
    steps:
      - name: Build API
        run: |
          echo "Run acceptance test agianes ${{ input.url}}"
          sleep 10s
