name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Run Api
    runs-on: ubuntu-latest
    steps:
      - name: Build API
        run: |
          echo "Run acceptance test agianes ${{ github.event.client_payload }} toJson('{"test": "1"}').test ${{ toJson(github.event.client_payload).url }}"
          sleep 10s
