name: BrowserStack Test Core PR
on:
  workflow_dispatch:

jobs:
  parse-data:
    runs-on: ubuntu-latest
    steps:
    - name: Get branch url
      uses: actions/checkout@v3
      with:
        url: ${{ github.event.inputs.url }}
    - run: echo ${{ github.event.inputs}}
          
