name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  parse-data:
    runs-on: ubuntu-latest
    steps:
    - name: Get branch url
      uses: actions/checkout@v3

    - name: Parse client_payload
      run: |
       payload=${{ toJson(github.event.client_payload) }}
       echo "Parsed Payload: $payload"
          
