name: BrowserStack Test Core PR
on:
  repository_dispatch:
    types: 'test-core-pr'

jobs:
  parse-data:
    runs-on: ubuntu-latest
    steps:
    - name: Get branch url
      uses: actions/checkout@v3
      with:
        url: ${{ github.event.inputs.client_payload.ur; }}
    - run: echo ${{ github.event.client_payload.url}}
          
