name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Parse client_payload 
        run: |
          echo "Parsed Payload"
          
