name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  parse-data:
    runs-on: ubuntu-latest
    steps:
    - name: Get branch url
      uses: actions/checkout@v2

    - name: Parse client_payload
      run: |
        payload="${{ github.event.client_payload }}"
        echo "Received Payload: $payload"
        
        # Parse JSON using jq
        parsed_data=$(echo "$payload" | jq .)
        echo "Parsed Data: $parsed_data"

          
